In [8]:
rows = 5
i = 1
while i <= rows:
    print("* " * i)
    i += 1


rows = 5
for i in range(1, rows + 1):
    print("* " * i)


* 
* * 
* * * 
* * * * 
* * * * * 
* 
* * 
* * * 
* * * * 
* * * * * 


In [29]:
n=5
i=1
while i<=n:
    print("* "*i)
    i+=1

* 
* * 
* * * 
* * * * 
* * * * * 


In [11]:
rows = 5
i = rows
while i > 0:
    print("* " * i)
    i -= 1


rows = 5
for i in range(rows, 0, -1):
    print("* " * i)

* * * * * 
* * * * 
* * * 
* * 
* 
* * * * * 
* * * * 
* * * 
* * 
* 


In [9]:
rows = 5
i = 1
while i <= rows:
    print(" " * (rows - i) + "* " * i)
    i += 1


rows = 5
for i in range(1, rows + 1):
    print(" " * (rows - i) + "* " * i)


    * 
   * * 
  * * * 
 * * * * 
* * * * * 
    * 
   * * 
  * * * 
 * * * * 
* * * * * 


In [4]:
rows = 5
i = 1
while i <= rows:
    print(" " * (rows - i) + "* " * i)
    i += 1

    * 
   * * 
  * * * 
 * * * * 
* * * * * 


In [5]:
rows = 5

# Upper half
i = 1
while i <= rows:
    print(" " * (rows - i) + "* " * i)
    i += 1

# Lower half
i = rows - 1
while i > 0:
    print(" " * (rows - i) + "* " * i)
    i -= 1

    * 
   * * 
  * * * 
 * * * * 
* * * * * 
 * * * * 
  * * * 
   * * 
    * 


In [6]:
rows = 5
i = 1
while i <= rows:
    j = 1
    while j <= i:
        print((i + j) % 2, end=" ")
        j += 1
    print()
    i += 1

0 
1 0 
0 1 0 
1 0 1 0 
0 1 0 1 0 


In [7]:
print(True+False*True)

1


In [10]:
rows = 5
for i in range(1, rows + 1):
    print((str(i) + " ") * i)


1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


In [12]:
rows = 5
num = 1
for i in range(1, rows + 1):
    for j in range(1, i + 1):
        print(num, end=" ")
        num += 1
    print()


1 
2 3 
4 5 6 
7 8 9 10 
11 12 13 14 15 


In [13]:
rows = 5
for i in range(1, rows + 1):
    for j in range(1, i + 1):
        print((i + j) % 2, end=" ")
    print()

0 
1 0 
0 1 0 
1 0 1 0 
0 1 0 1 0 


In [14]:
rows = 5
for i in range(rows):
    print(" " * (rows - i), end="")
    num = 1
    for j in range(i + 1):
        print(num, end=" ")
        num = num * (i - j) // (j + 1)
    print()

     1 
    1 1 
   1 2 1 
  1 3 3 1 
 1 4 6 4 1 


In [15]:
rows = 5
for i in range(rows, 0, -1):
    for j in range(1, i + 1):
        print(j, end=" ")
    print()


1 2 3 4 5 
1 2 3 4 
1 2 3 
1 2 
1 


In [17]:
rows = 5
i = rows
while i > 0:
    print("* " * i)
    i -= 1

rows = 5
for i in range(rows, 0, -1):
    print("* " * i)


* * * * * 
* * * * 
* * * 
* * 
* 
* * * * * 
* * * * 
* * * 
* * 
* 


In [18]:
rows = 5
i = rows

while i > 0:
    print(" " * (rows - i) + "* " * i)
    i -= 1


rows = 5

for i in range(rows, 0, -1):
    print(" " * (rows - i) + "* " * i)


* * * * * 
 * * * * 
  * * * 
   * * 
    * 
* * * * * 
 * * * * 
  * * * 
   * * 
    * 


In [20]:
rows = 5
i = rows

while i > 0:
    if i % 2 != 0:  # Only print odd rows
        print(" " * (rows - i) + "* " * i)
    i -= 1



rows = 5

for i in range(rows, 0, -1):
    if i % 2 != 0:  # Only print odd rows
        print(" " * (rows - i) + "* " * i)


* * * * * 
  * * * 
    * 
* * * * * 
  * * * 
    * 


# OOPS Concepts-------------------------->

In [23]:
'''Encapsulation
Definition: Encapsulation is the concept of bundling data (attributes) and methods (functions) within a single unit, or class, and restricting 
access to some of an object's components'''

class Car:
    def __init__(self, brand, year):
        self.brand = brand       # Public attribute
        self.__year = year       # Private attribute

    def get_year(self):          # Getter for the private attribute
        return self.__year

    def set_year(self, year):    # Setter for the private attribute
        if year > 2000:
            self.__year = year

car = Car("Toyota", 2015)
print(car.brand)  # Accessing public attribute
print(car.get_year())  # Accessing private attribute using getter

Toyota
2015


In [24]:
'''Inheritance
Definition: Inheritance allows one class (child class) to inherit the attributes and methods of another class (parent class). 
This promotes code reuse and establishes a relationship between classes.'''
# Single Inheritance
class Animal:
    def speak(self):
        return "Some sound"

class Dog(Animal):          # Dog inherits from Animal
    def bark(self):
        return "Woof!"

dog = Dog()
print(dog.speak())          # Inherited method
print(dog.bark())           # Method from Dog class

Some sound
Woof!


In [25]:
# Method Overriding Example
class Animal:
    def speak(self):
        return "Some sound"

class Dog(Animal):
    def speak(self):        # Overriding the parent class method
        return "Woof!"

class Cat(Animal):
    def speak(self):        # Overriding the parent class method
        return "Meow!"

animals = [Dog(), Cat()]

for animal in animals:
    print(animal.speak())   # Calls the overridden method based on the object type

Woof!
Meow!


In [26]:
'''Abstraction
Definition: Abstraction hides the implementation details and shows only the necessary features of an object. 
In Python, abstraction is achieved using abstract classes and methods.'''

from abc import ABC, abstractmethod

class Shape(ABC):
    @abstractmethod
    def area(self):
        pass

    @abstractmethod
    def perimeter(self):
        pass

class Rectangle(Shape):
    def __init__(self, width, height):
        self.width = width
        self.height = height

    def area(self):
        return self.width * self.height

    def perimeter(self):
        return 2 * (self.width + self.height)

rectangle = Rectangle(4, 5)
print("Area:", rectangle.area())
print("Perimeter:", rectangle.perimeter())

Area: 20
Perimeter: 18


In [27]:
Summary of OOP Concepts in Python
Encapsulation: Hiding internal details and exposing only what is necessary.
Inheritance: Establishing a hierarchy between classes for code reuse.
Polymorphism: Using the same interface for different objects.
Abstraction: Focusing on essential qualities, hiding the implementation details.

SyntaxError: invalid syntax (2911599626.py, line 1)

# Important Basic Q&A in Python:

In [35]:
# Question: Write a function to reverse a given string.
def reverse_string(s):
    return s[::-1]

# Test
S="Food"
print(reverse_string(S)) 
print(reverse_string("hello"))  # Output: "olleh"

dooF
olleh


In [36]:
# Question: Write a function to check if a number is prime.

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True

# Test
print(is_prime(11))  # Output: True
print(is_prime(4))   # Output: False

True
False


In [37]:
#Question: Write a Python function to find the largest element in a list?
def find_largest(numbers):
    return max(numbers)

# Test
print(find_largest([1, 5, 3, 9, 2]))  # Output: 9

9


In [54]:
# Question: Write a function to check if a string is a palindrome (the same forwards and backwards).
def is_palindrome(s):
    return s == s[::-1]

# Test
print(is_palindrome("racecar"))  # Output: True
print(is_palindrome("hello"))    # Output: False

if(is_palindrome("hello")==True):
    print("It is a palindrome")
else:
    print("It is not a palindrome")


True
False
It is not a palindrome


In [39]:
# Question: Write a function to find the factorial of a number?

def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)

# Test
print(factorial(5))  # Output: 120

120


In [41]:
# Question: Write a function to generate the Fibonacci series up to n terms.

def fibonacci(n):
    fib_series = [0, 1]
    for i in range(2, n):
        fib_series.append(fib_series[-1] + fib_series[-2])
    return fib_series[:n]

# Test
print(fibonacci(10))  # Output: [0, 1, 1, 2, 3]

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


In [42]:
# Question: Write a function to remove duplicates from a list.

def remove_duplicates(lst):
    return list(set(lst))

# Test
print(remove_duplicates([1, 2, 3, 2, 1, 4]))  # Output: [1, 2, 3, 4] (order may vary)

[1, 2, 3, 4]


In [43]:
# Question: Write a function to count the number of vowels in a given string?
def count_vowels(s):
    vowels = "aeiouAEIOU"
    return sum(1 for char in s if char in vowels)

# Test
print(count_vowels("hello"))  # Output: 2


2


In [44]:
# Question: Write a function to find the second largest element in a list?

def second_largest(numbers):
    unique_numbers = list(set(numbers))
    unique_numbers.sort()
    return unique_numbers[-2] if len(unique_numbers) >= 2 else None

# Test
print(second_largest([1, 2, 3, 4, 5]))  # Output: 4
print(second_largest([5, 5, 5]))       # Output: None

4
None


In [45]:
# Write a function to merge two sorted lists into a single sorted list?

def merge_sorted_lists(list1, list2):
    return sorted(list1 + list2)

# Test
print(merge_sorted_lists([1, 3, 5], [2, 4, 6]))  # Output: [1, 2, 3, 4, 5, 6]

[1, 2, 3, 4, 5, 6]


In [46]:
# Write a function to count the frequency of each element in a list?

from collections import Counter

def count_frequency(lst):
    return dict(Counter(lst))

# Test
print(count_frequency([1, 2, 2, 3, 3, 3]))  # Output: {1: 1, 2: 2, 3: 3}

{1: 1, 2: 2, 3: 3}


In [47]:
# Question: Write a function to find the common elements between two lists.

def common_elements(list1, list2):
    return list(set(list1) & set(list2))

# Test
print(common_elements([1, 2, 3], [2, 3, 4]))  # Output: [2, 3]


[2, 3]


In [48]:
# Write a function to check if a list is sorted in ascending order.

def is_sorted(lst):
    return lst == sorted(lst)

# Test
print(is_sorted([1, 2, 3]))      # Output: True
print(is_sorted([3, 2, 1]))      # Output: False

True
False


In [49]:
# Question: Write a function to find the length of the longest word in a sentence?

def longest_word_length(sentence):
    words = sentence.split()
    return max(len(word) for word in words)

# Test
print(longest_word_length("Python is fun"))  # Output: 6

6


In [50]:
# Question: Write a function to flatten a nested list.

def flatten_list(nested_list):
    flat_list = []
    for item in nested_list:
        if isinstance(item, list):
            flat_list.extend(flatten_list(item))
        else:
            flat_list.append(item)
    return flat_list

# Test
print(flatten_list([1, [2, 3], [4, [5, 6]]]))  # Output: [1, 2, 3, 4, 5, 6]

[1, 2, 3, 4, 5, 6]


# NUMPY & PYTHON:

In [55]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
What is the difference between a Python list and a NumPy array?

Answer:

Python List: Can store elements of different types and has higher memory overhead.
NumPy Array: Stores elements of the same type and is more efficient in terms of performance and memory.

In [56]:
# How do you create a NumPy array with zeros or ones?

import numpy as np
zero_arr = np.zeros((3, 3))  # 3x3 array of zeros
ones_arr = np.ones((2, 4))   # 2x4 array of ones
print(zero_arr)
print(ones_arr)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [57]:
# How do you perform element-wise operations in NumPy?
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = arr1 + arr2  # Element-wise addition
print(result)

[5 7 9]


In [58]:
# How do you reshape a NumPy array?
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [59]:
# How do you calculate the mean, median, and standard deviation in NumPy?

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))

Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951


In [60]:
# How do you filter values in a NumPy array based on a condition?

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
filtered_arr = arr[arr > 3]  # Filter elements greater than 3
print(filtered_arr)

[4 5 6]


# Pandas:

In [61]:
# How do you create a DataFrame in Pandas?
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}
df = pd.DataFrame(data)
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


In [63]:
# How do you access a specific column in a Pandas DataFrame?
print(df['Name'])

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object


In [64]:
# How do you filter rows in a Pandas DataFrame based on a condition?

import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}
df = pd.DataFrame(data)
filtered_df = df[df['Age'] > 30]  # Filter rows where Age > 30
print(filtered_df)

      Name  Age
2  Charlie   35


In [65]:
# How do you add a new column to a Pandas DataFrame?

import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}
df = pd.DataFrame(data)
df['Gender'] = ['F', 'M', 'M']
print(df)

      Name  Age Gender
0    Alice   25      F
1      Bob   30      M
2  Charlie   35      M


In [66]:
# How do you handle missing values in a Pandas DataFrame?

import pandas as pd
data = {'Name': ['Alice', 'Bob', None], 'Age': [25, None, 35]}
df = pd.DataFrame(data)
df_filled = df.fillna('Unknown')  # Fill missing values with 'Unknown'
print(df_filled)

      Name      Age
0    Alice     25.0
1      Bob  Unknown
2  Unknown     35.0


In [67]:
# How do you group data in Pandas?
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Alice', 'Bob'], 'Score': [90, 80, 85, 75]}
df = pd.DataFrame(data)
grouped_df = df.groupby('Name').sum()  # Group by Name and calculate sum of Score
print(grouped_df)

       Score
Name        
Alice    175
Bob      155


In [68]:
# How do you merge two DataFrames in Pandas?
import pandas as pd
df1 = pd.DataFrame({'ID': [1, 2, 3], 'Name': ['Alice', 'Bob', 'Charlie']})
df2 = pd.DataFrame({'ID': [2, 3, 4], 'Age': [30, 35, 40]})
merged_df = pd.merge(df1, df2, on='ID', how='inner')
print(merged_df)

   ID     Name  Age
0   2      Bob   30
1   3  Charlie   35
